# Generated by Django 6.0.4 on 2026-04-20 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ant', models.CharField(max_length=15)),
                ('estado_nvo', models.CharField(max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='postulaciones.postulante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('REGISTRO', 'Registro de usuario'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('GUARDAR_PROGRESO', 'Guardar progreso formulario'), ('ENVIAR_POSTULACION', 'Envío de postulación'), ('EDITAR_SECCION', 'Edición de sección'), ('ELIMINAR_ITEM', 'Eliminación de ítem'), ('SUBIR_DOCUMENTO', 'Subida de documento PDF'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ADMIN_ACCION', 'Acción de administrador')], max_length=25)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de acción',
                'verbose_name_plural': 'Logs de acciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACTIVACION', 'Activación de cuenta'), ('RECUPERACION', 'Recuperación de contraseña'), ('CONFIRMACION', 'Confirmación de postulación'), ('RESULTADO_ETAPA', 'Resultado de etapa'), ('HABILITADO', 'Postulante habilitado'), ('INHABILITADO', 'Postulante inhabilitado'), ('EVALUACION', 'Acceso a evaluación técnica'), ('CALIFICACION', 'Notificación de calificación')], max_length=20)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('enviado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Notificación email',
                'verbose_name_plural': 'Notificaciones email',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SesionPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de postulante',
                'verbose_name_plural': 'Sesiones de postulantes',
                'ordering': ['-inicio'],
            },
        ),
    ]
