# Generated by Django 6.0.4 on 2026-04-20 21:53

import django.db.models.deletion
import postulaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(blank=True, max_length=20, unique=True)),
                ('sector', models.CharField(blank=True, choices=[('AFILIADO', 'Miembro Principal y Alterno — Sector Afiliados'), ('JUBILADO', 'Miembro Principal y Alterno — Sector Jubilados'), ('EMPLEADOR', 'Miembro Principal y Alterno — Sector Empleador')], max_length=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('EN_REVISION', 'En revisión'), ('HABILITADO', 'Habilitado'), ('INHABILITADO', 'Inhabilitado'), ('FASE_MERITOS', 'Fase de méritos'), ('EVAL_TECNICA', 'Evaluación técnica'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=15)),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=10)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=60)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_HECHO', 'Unión de hecho')], max_length=15)),
                ('conyuge_nombres', models.CharField(blank=True, max_length=100)),
                ('conyuge_cedula', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=80)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('calle_principal', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=15)),
                ('calle_secundaria', models.CharField(blank=True, max_length=150)),
                ('sector_domicilio', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=250)),
                ('telefono_celular', models.CharField(blank=True, max_length=15)),
                ('telefono_domicilio', models.CharField(blank=True, max_length=15)),
                ('email_secundario', models.EmailField(blank=True, max_length=254)),
                ('tiene_organizacion', models.BooleanField(blank=True, null=True)),
                ('nombre_organizacion', models.CharField(blank=True, max_length=200)),
                ('doc_organizacion', models.FileField(blank=True, null=True, upload_to='organizaciones/', validators=[postulaciones.models.validar_pdf])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
            },
        ),
        migrations.CreateModel(
            name='Inhabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_goce_derechos', models.BooleanField(null=True)),
                ('p2_inhabilitado_comercio', models.BooleanField(null=True)),
                ('p3_mora_obligaciones', models.BooleanField(null=True)),
                ('p4_vinculo_financiero', models.BooleanField(null=True)),
                ('p5_funcionario_iess', models.BooleanField(null=True)),
                ('p6_interes_aseguradoras', models.BooleanField(null=True)),
                ('p7_removido_organismo', models.BooleanField(null=True)),
                ('p7_institucion', models.CharField(blank=True, max_length=100)),
                ('p7_cargo', models.CharField(blank=True, max_length=100)),
                ('p7_fecha_fin', models.DateField(blank=True, null=True)),
                ('p7_motivo', models.CharField(blank=True, max_length=300)),
                ('p8_sri', models.BooleanField(null=True)),
                ('p9_castigo_financiero', models.BooleanField(null=True)),
                ('p10_litigio_iess', models.BooleanField(null=True)),
                ('p11_procesado_corrupcion', models.BooleanField(null=True)),
                ('p12_contraloria', models.BooleanField(null=True)),
                ('p13_uafe', models.BooleanField(null=True)),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inhabilidades', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Inhabilidades',
                'verbose_name_plural': 'Inhabilidades',
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('TERCER', 'Tercer nivel de grado'), ('ESP', 'Cuarto nivel — Especialidad académica'), ('MAESTRIA', 'Cuarto nivel — Maestría académica'), ('PHD', 'Cuarto nivel PhD — Doctorado')], max_length=10)),
                ('institucion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('EXTRANJERA', 'Extranjera')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('area_estudios', models.CharField(choices=[('FINANZAS', 'Finanzas'), ('MERCADO_CAP', 'Mercado de capitales'), ('ADMIN', 'Administración de empresas'), ('ECONOMIA', 'Economía'), ('DERECHO', 'Derecho'), ('AFINES', 'Materias afines')], max_length=15)),
                ('num_senescyt', models.CharField(max_length=50)),
                ('fecha_senescyt', models.DateField()),
                ('documento', models.FileField(upload_to='formacion/', validators=[postulaciones.models.validar_pdf])),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Formación académica',
                'verbose_name_plural': 'Formaciones académicas',
                'ordering': ['-fecha_senescyt'],
            },
        ),
        migrations.CreateModel(
            name='FamiliarIESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('parentesco', models.CharField(choices=[('CONYUGE', 'Cónyuge'), ('CONVIVIENTE', 'Conviviente'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano/a'), ('CUÑADO', 'Cuñado/a'), ('SUEGRO', 'Suegro/a'), ('YERNO', 'Yerno'), ('NUERA', 'Nuera'), ('NIETO', 'Nieto/a'), ('TIO', 'Tío/a'), ('SOBRINO', 'Sobrino/a'), ('PRIMO_HERMANO', 'Primo hermano/a'), ('HIJO_POLITICO', 'Hijo político')], max_length=20)),
                ('institucion', models.CharField(choices=[('IESS', 'IESS'), ('BIESS', 'BIESS')], max_length=5)),
                ('area', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Familiar en IESS/BIESS',
                'verbose_name_plural': 'Familiares en IESS/BIESS',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('DIRECCION', 'Dirección')], max_length=10)),
                ('cargo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('actividades_area', models.CharField(choices=[('FINANZAS', 'Finanzas'), ('MERCADO_CAP', 'Mercado de capitales'), ('ADMIN', 'Administración de empresas'), ('ECONOMIA', 'Economía'), ('DERECHO', 'Derecho'), ('AFINES', 'Materias afines')], max_length=15)),
                ('descripcion', models.TextField(max_length=1000)),
                ('documento', models.FileField(upload_to='experiencia/', validators=[postulaciones.models.validar_pdf])),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Experiencia profesional',
                'verbose_name_plural': 'Experiencias profesionales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CURSO', 'Curso'), ('SEMINARIO', 'Seminario'), ('TALLER', 'Taller')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas', models.PositiveIntegerField()),
                ('documento', models.FileField(upload_to='capacitacion/', validators=[postulaciones.models.validar_pdf])),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('PUBLICACION', 'Publicación'), ('INVESTIGACION', 'Trabajo de investigación')], max_length=15)),
                ('medio', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('relacionado', models.BooleanField(default=False)),
                ('documento', models.FileField(upload_to='publicaciones/', validators=[postulaciones.models.validar_pdf])),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='postulaciones.postulante')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
