# Generated by Django 6.0.4 on 2026-05-06 16:25

import postulaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='sectores_disponibles',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='documento',
            field=models.FileField(upload_to=postulaciones.models.upload_capacitacion, validators=[postulaciones.models.validar_pdf]),
        ),
        migrations.AlterField(
            model_name='experienciaprofesional',
            name='documento',
            field=models.FileField(upload_to=postulaciones.models.upload_experiencia, validators=[postulaciones.models.validar_pdf]),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='documento',
            field=models.FileField(upload_to=postulaciones.models.upload_formacion, validators=[postulaciones.models.validar_pdf]),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='doc_organizacion',
            field=models.FileField(blank=True, null=True, upload_to=postulaciones.models.upload_organizacion, validators=[postulaciones.models.validar_pdf]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='documento',
            field=models.FileField(upload_to=postulaciones.models.upload_publicacion, validators=[postulaciones.models.validar_pdf]),
        ),
    ]
