# Generated by Django 6.0.4 on 2026-05-06 18:36

import postulaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_postulante_sectores_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='constancia',
            field=models.FileField(blank=True, null=True, upload_to=postulaciones.models.upload_constancia, validators=[postulaciones.models.validar_pdf_2mb]),
        ),
        migrations.AddField(
            model_name='postulante',
            name='declaracion_juramentada',
            field=models.FileField(blank=True, null=True, upload_to=postulaciones.models.upload_declaracion_juramentada, validators=[postulaciones.models.validar_pdf_2mb]),
        ),
    ]
