# Generated by Django 6.0.4 on 2026-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulanteuser',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
