# Generated by Django 6.0.4 on 2026-04-29 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_postulanteuser_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('expira', models.DateTimeField()),
                ('verificado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
